<?php

/**
 * @file
 * Contains noticias.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function noticias_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the noticias module.
    case 'help.page.noticias':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Noticias de bootcamp') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function noticias_theme() {
  return [
    'noticias' => [
      'render element' => 'children',
    ],
  ];
}
