<?php

/**
 * @file
 * Contains miblog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function miblog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the miblog module.
    case 'help.page.miblog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mi blog de drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function miblog_theme() {
  return [
    'miblog' => [
      'render element' => 'children',
    ],
  ];
}
